### ISSUE TITLE
[Bug]: 上课到下课下课间与两个非上课时间段间切换时倒计时位移异常

### ISSUE THREAD

**Issue by daizihan233** [daizihan233/ElectronClassSchedule#3]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。
- [X] 我确定在最近的 commit 提交所对应的版本中仍未修复

### 为了确保你是人类，请阅读并勾选以下内容，如有错选本仓库所有者可能会直接关闭此 Issue。

- [X] 我保证我已经认真阅读了以上说明，并已经勾选上面的选项
- [ ] 我不确定我有认真阅读了以上说明，并没有勾选了上面的选项
- [ ] 我确定我没有已经认真阅读了以上说明，并已经勾选上面的选项
- [X] 我不否认我确认了我已经认真阅读了以上说明，并否认我确定没有勾选上面的选项
- [ ] 我确定我没有认真阅读了以上说明，并没有勾选上面的选项
- [X] 我不确定我没有认真阅读了以上说明，并勾选了上面的选项
- [ ] 我承诺我以上所勾选的信息是不属实的
- [X] 我承诺我以上所勾选的信息不是错误的

### 您使用的配置文件类别是？

云端链接

### 配置文件

任意

### 您反馈的问题属于以下哪个功能？

课表显示

### 您反馈的问题属于以下哪个类别？

功能异常

### 重现步骤

1. 打开课表程序
2. 开启“下课隐藏”
3. 等待任意一节课上课
4. 等待这节课变为下课状态，并观察倒计时位移

### 期望的结果是什么？

![图片](https://github.com/daizihan233/ElectronClassSchedule/assets/72146468/8121806c-7035-47c5-8a4f-1c4706437242)

倒计时从上一个状态（这节课上课）位移到当前状态（这节课下课）

### 实际的结果是什么？

![图片](https://github.com/daizihan233/ElectronClassSchedule/assets/72146468/23df3b6f-6bbd-40f4-96b7-3ab9f9b5680b)

错误地从下一个状态向前位移到了当前状态

### 补充说明（可选）

![图片](https://github.com/daizihan233/ElectronClassSchedule/assets/72146468/b6369655-5d1d-40cf-b549-1c68c0c05b3f)

在存在两个非上课时间段的时间段，位移应该保持不动，但依然是从下一个状态位移到了当前状态

**Comment by daizihan233** [comment]
> 参考iOS灵动岛（？

计划打算是这样的，会显示一个简单的移动动画

不然总有~~啥比~~同学会跟我说反直觉

**Comment by Chentaiyu114514** [comment]
> > 参考iOS灵动岛（？
> 
> 计划打算是这样的，会显示一个简单的移动动画
> 
> 不然总有~啥比~同学会跟我说反直觉

那种~弱智~就别管了 乱说话就让他搞（

**Comment by daizihan233** [comment]
# Bug 原因
Bug 出在文件 `index.html` 中的 `setCountdownerPosition` 函数，该函数在动态计算倒计时位置时，进行了如下计算：
```js
offset = {
  x: highlightElement.offsetLeft - countdownContainer.offsetWidth / 2 + highlightElement.offsetWidth / 2,
  y: classContainer.offsetHeight
}
```
其中，使用到了 `countdownContainer.offsetWidth` ，而该值在开启 *上课隐藏* 的情况下，由于 `countdownContainer` 的 `display` 属性为 `none` （即不显示），所以该值等于 0，导致了计算错误

**Comment by daizihan233** [comment]
# 修复过程
新建一个变量作为缓存
```js
let cacheCountdownContainerOffsetWidth = countdownContainer.offsetWidth
```
使用时，先判断是否隐藏，如果没有隐藏则更新
```js
if (countdownContainer.style.display !== 'none')
  cacheCountdownContainerOffsetWidth = countdownContainer.offsetWidth
```
反之，如果有，则不做任何操作，使用缓存的值继续计算
