### ISSUE TITLE
[Bug?]: 使用上课隐藏下课时倒计时位移异常(?

### ISSUE THREAD

**Issue by Chentaiyu114514** [daizihan233/ElectronClassSchedule#7]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。
- [X] 我确定在最近的 commit 提交所对应的版本中仍未修复

### 为了确保你是人类，请阅读并勾选以下内容，如有错选本仓库所有者可能会直接关闭此 Issue。

- [X] 我保证我已经认真阅读了以上说明，并已经勾选上面的选项
- [ ] 我不确定我有认真阅读了以上说明，并没有勾选了上面的选项
- [ ] 我确定我没有已经认真阅读了以上说明，并已经勾选上面的选项
- [x] 我不否认我确认了我已经认真阅读了以上说明，并否认我确定没有勾选上面的选项
- [ ] 我确定我没有认真阅读了以上说明，并没有勾选上面的选项
- [x] 我不确定我没有认真阅读了以上说明，并勾选了上面的选项
- [ ] 我承诺我以上所勾选的信息是不属实的
- [X] 我承诺我以上所勾选的信息不是错误的

### 您使用的配置文件类别是？

云端链接

### 配置文件

任意

### 您反馈的问题属于以下哪个功能？

课表显示

### 您反馈的问题属于以下哪个类别？

功能异常

### 重现步骤

1. 打开课表程序
2. 打开上课隐藏
3. 等到下课的位移出现

### 期望的结果是什么？

正常位移

### 实际的结果是什么？

错误的从下一节课的课间移动到当前位置
![IMG_20240615_151548](https://github.com/daizihan233/ElectronClassSchedule/assets/169056337/65077d29-7d25-45b5-bf49-1c6600c0f516)

**Comment by daizihan233** [comment]
duplicated #3
