### ISSUE TITLE
[新功能?]: 自定义横幅

### ISSUE THREAD

**Issue by daizihan233** [daizihan233/ElectronClassSchedule#8]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是一个伪需求。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。
- [X] 我确定在最近的 commit 提交所对应的版本中没有这个功能

### 为了确保你是人类，请阅读并勾选以下内容，如有错选本仓库所有者可能会直接关闭此 Issue。

- [X] 我保证我已经认真阅读了以上说明，并已经勾选上面的选项
- [ ] 我不确定我有认真阅读了以上说明，并没有勾选了上面的选项
- [ ] 我确定我没有已经认真阅读了以上说明，并已经勾选上面的选项
- [X] 我不否认我确认了我已经认真阅读了以上说明，并否认我确定没有勾选上面的选项
- [ ] 我确定我没有认真阅读了以上说明，并没有勾选上面的选项
- [X] 我不确定我没有认真阅读了以上说明，并勾选了上面的选项
- [ ] 我承诺我以上所勾选的信息是不属实的
- [X] 我承诺我以上所勾选的信息不是错误的

### 新功能名称

自定义横幅

### 新功能描述

增加一个自定义的横幅，到了某节课就自动展示，用于家长会之类的场景

### 新功能意义

现在的横幅仅限家长会可用，可以增加一个自定义的版本，这样就可以在云端控制了

**Comment by Chentaiyu114514** [comment]
滚动字幕可能会代替这一项（？

**Comment by daizihan233** [comment]
> 滚动字幕可能会代替这一项（？

有道理，那就跟 #5 合并在一起了
